### ISSUE TITLE
[US-01] Start page

### ISSUE THREAD

**Issue by stschuessler** [stschuessler/capstone-project#1]
## Value Statement
As a User I want to see the start page when I open my App

## Mockup
![Wardrobe](https://nl.123rf.com/photo_50761643_hand-drawn-wardrobe-sketch.-furniture-for-clothes..html)

## Acceptance Criteria
- App shows image of wardrobe

## Tasks
- [ ] Create React App
- [ ] Create Component
- [ ] Write Component Tests
- [ ] Add Component to App
