### ISSUE TITLE
Render page with all clothing entries

### ISSUE THREAD

**Issue by stschuessler** [stschuessler/capstone-project#1]
## Value Statement
As a User I want to see all clothing entries.

## Mockup
<img width="328" alt="mockup-categories-alternative2" src="https://user-images.githubusercontent.com/5842609/136528293-8396c73a-eae9-4f33-ae53-795391dc2dd7.png">

## Acceptance Criteria
- App shows all clothe items of the selected category
- Scrolling function up/down

## Tasks
- [x] Create Clothe Component
- [x] Define/add Array with test content
- [x] Render all Clothe Components
- [x] Write testing

## Complexity
- low
