### ISSUE TITLE
Create new entry

### ISSUE THREAD

**Issue by stschuessler** [stschuessler/capstone-project#12]
## Value Statement
As a User I want to have a form with the possibility to add a new Clothing card. 

## Mockup
<img width="290" alt="mockup-create-new-page" src="https://user-images.githubusercontent.com/5842609/139256650-aedd64c0-fde2-48eb-a5ba-1f3188fd613e.png">

## Acceptance Criteria
- Button with "New entry" on the Clothing list page
- Form with: 
- Input for the clothing name and uploading images
- Checkboxes for detail informations
- Button/ link back to Clothing list page 

## Tasks
- [x] Create form component with create button
- [x] Create form with button to submit, button to reset and button to exit the form
- [x] Store submitted data in localStorage
- [x] Writing test 
- [x] Writing storybook

## Complexity
- medium
