### ISSUE TITLE
Create Outfit Component

### ISSUE THREAD

**Issue by stschuessler** [stschuessler/capstone-project#14]
## Value Statement
As a User I want to see all entries of my Outfits. 

## Mockup
<img width="328" alt="mockup-categories-alternative2" src="https://user-images.githubusercontent.com/5842609/136528293-8396c73a-eae9-4f33-ae53-795391dc2dd7.png">

## Acceptance Criteria
- App shows all Outfit images that are registered
- A button with the name Outfit which is shown in the details of the clothing card

## Tasks
- [ ] Create Outfit Button
- [ ] Add property to Mock-Data Array 
- [ ] Filter function for Outfit entries 
- [ ] Render all Outfit entries
- [ ] Write testing
- [ ] Write storybook

## Complexity
- medium
