### ISSUE TITLE
Create Category Component

### ISSUE THREAD

**Issue by stschuessler** [stschuessler/capstone-project#16]
## Value Statement
As a User I want to have the possibility to chose between different clothing categories.

## Mockup
<img width="328" alt="mockup-clothing-categoeries" src="https://user-images.githubusercontent.com/5842609/138610836-7932a683-93d3-4e8b-a40f-78db98e238e8.png">

## Acceptance Criteria
- By clicking a category button or link, all choosing options of the different kinds of clothing categories will become visible as checkboxes
- There are three options given to process (not all function implemented in this user story) via three buttons: 
either to load the chosen categories, to reset the form and to hide the category options 

## Tasks
- [x] Create Category Component
- [x] Add category properties in mockup-data file
- [x] Filter all category entries in a new array. Make sure that each category is unique within the array.
- [x] Set a new useState variable for the categories
- [x] For each category generate a checkbox
- [x] Add three buttons with text like 'Load', 'Clear' and 'Cancel'
- [x] The 'Cancel' button causes the checkboxes to become invisible
- [x] The 'Clear' button causes the checkboxes to reset
- [x] Write testing
- [x] Write storybook

## Complexity
- medium
