### ISSUE TITLE
Create Start page

### ISSUE THREAD

**Issue by stschuessler** [stschuessler/capstone-project#19]
## Value Statement
As a User I see the image of a wardrobe when I start the App. By clicking an 'entry' button the App load me to a list of all my entries.

## Acceptance Criteria
- App shows images of wardrobe.
- App shows button which renders all entries of the saved garments.

## Tasks
- [x] Rename App component as ClothingApp component
- [x] Implement new state variable
- [x] Implement start image in App
- [x] Implement ClothingApp component
- [x] Invoke ClothingApp component/ change state by clicking button
- [ ] Write testing
- [ ] Write storybook

## Complexity
- easy
