### ISSUE TITLE
Switch to details of clothing item

### ISSUE THREAD

**Issue by stschuessler** [stschuessler/capstone-project#4]
## Value Statement
As a User I want to switch to a specific entry by clicking on the picture of interest.

## Mockup
<img width="304" alt="mockup-select-entry" src="https://user-images.githubusercontent.com/5842609/136530773-efa9ae88-86e1-44ad-8b28-0ae164605c51.png"> <img width="228" alt="mockup-clothe-full-screen" src="https://user-images.githubusercontent.com/5842609/136522839-d7265d89-403a-48c2-93ab-95f2619eda2b.png">

## Acceptance Criteria
- Pictures of clothing items works as buttons
- By clicking a certain button the page renders the details of the selected item 

## Tasks
- [ ] Define picture as a button/ Button Component
- [ ] Add onClick event
- [ ] Change state of App/Clothe Component invoked by the onClick event from the button

## Complexity
- medium
