### ISSUE TITLE
Add button with text "back"

### ISSUE THREAD

**Issue by stschuessler** [stschuessler/capstone-project#5]
## Value Statement
As a User I can see a button with the content "back".

## Mockup
<img width="313" alt="mockup-back-button" src="https://user-images.githubusercontent.com/5842609/136527537-1ecec6cb-969b-4425-864d-98045dc07f5e.png">

## Acceptance Criteria
- The page has a "backwards" button

## Tasks
- [ ] Create Button Component
- [ ] Add html elements
- [ ] Write test
- [ ] Positioning of Button
- [ ] Button Styling

## Complexity
- light
